[package]
name = "spacerocks"
version = "0.2.0-alpha.0"
edition = "2021"
authors = ["Kevin Napier"]
description = "Software for solar system calculations."
repository = "https://github.com/kjnapier/spacerocks"
license = "GPL-3.0"
include = ["/src"]

[dependencies]

nalgebra = "0.32.2"


reqwest = { version = "0.11.4", features = ["json", "blocking"] }
lazy_static = "1.4.0"
phf = {version = "0.11.2", features = ["macros"]}
chrono = "0.4.19"
rayon = "1.9"
memmap2 = "0.9"
flate2 = "1"
tar = "0.4"

thiserror = "2"

serde = { version = "1.0.197", features = ["derive", "rc"]}
serde_json = "1.0.68"

rand = "0.8.5"

toml = "0.8"
dirs = "6"
strsim = "0.11.1"

# plotly = { version = "0.8", features = ["kaleido"] }
